server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/movie_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


pagehelper:
  helper-dialect: mysql   # 指定数据库类型为 MySQL
  reasonable: true        # 如果页码小于 1，自动调整为第一页
  support-methods-arguments: true  # 支持接口直接传递分页参数
  params: count=countSql  # 自动生成 count 查询语句

# 文件上传的前缀url
fileBaseUrl: http://localhost:9090